#!/usr/bin/env bash
#
# bootstrap installs things.

set -e

HERE="$(dirname $0)"
source "${HERE}/helpers"
cd "${HERE}/.."

DOTFILES_ROOT=$(pwd -P)

setup_gitconfig() {
  if ! [ -f "${DOTFILES_ROOT}/git/gitconfig.local.symlink" ]
  then
    info 'setup gitconfig'

    git_credential='cache'
    if is_macos
    then
      git_credential='osxkeychain'
    fi

    user ' - What is your github author name?'
    read -e git_authorname
    user ' - What is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.local.symlink.example > git/gitconfig.local.symlink

    success 'gitconfig'
  fi
}

link_file() {
  local src=$1 dst=$2

  local overwrite= backup= skip=
  local action=

  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
  then

    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
    then

      local currentSrc="$(readlink $dst)"

      if [ "$currentSrc" == "$src" ]
      then
        skip=true;

      else
        user "File already exists: ${YELLOW}${dst}${RESET} (${MAGENTA}$(basename "$src")${RESET}), what do you want to do?\n\
        [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            ;;
        esac
      fi
    fi

    overwrite=${overwrite:-$overwrite_all}
    backup=${backup:-$backup_all}
    skip=${skip:-$skip_all}

    if [ "$overwrite" == "true" ]
    then
      rm -rf "$dst"
      success "removed $dst"
    fi

    if [ "$backup" == "true" ]
    then
      mv "$dst" "${dst}.backup"
      success "moved $dst to ${dst}.backup"
    fi

    if [ "$skip" == "true" ]
    then
      success "skipped $src"
    fi
  fi

  if [ "$skip" != "true" ]  # "false" or empty
  then
    ln -s "$1" "$2"
    success "linked $1 to $2"
  fi
}

install_dotfiles() {
  info 'installing dotfiles'

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

echo ''

# setup_gitconfig
install_dotfiles

# If we're on a Mac, let's install and setup homebrew.
if is_macos
then
  info "setting Mac defaults"
  $DOTFILES_ROOT/macos/set-defaults.sh

  [ ! $(which brew) ] && $DOTFILES_ROOT/homebrew/install.sh 2>&1

  info "updating brew"
  brew update -q
  success "brew updated"

  info "upgrading brew apps"
  brew upgrade -q
  success "apps upgraded"

  info "running topic installers"
  $DOTFILES_ROOT/script/install
fi

echo ''
echo -e "${MAGENTA}> System Ready!${RESET}"
