#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

HERE="$(dirname $0)"
source "${HERE}/helpers"
cd "${HERE}/.."

# find the installers and run them iteratively
find . -name install.sh | while read installer
do
    sh -c "${installer}"
    success "ran ${installer}"
done
